name: Streamlit CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests (optional)
      - name: Run tests
        run: |
          # Example: Run pytest if you have tests
          # pytest
          echo "No tests configured"

      # Step 5: Deploy (test run in CI)
      - name: Run Streamlit app
        run: |
          nohup streamlit run app.py --server.port 8501 &
          sleep 10
          echo "Streamlit app is running for test"
